name: CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build with GHC ${{ matrix.ghc }}
    strategy:
      matrix:
        ghc: ['7.10.3', '8.0.2', '8.2.2', '8.4.4', '8.6.5', '8.8.4', '8.10.5', '9.0.1']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Haskell
      uses: haskell/actions/setup@v1.2.3
      with:
        ghc-version: ${{ matrix.ghc }}
    - name: Build and Test
      shell: bash
      run: |
        cabal v2-build all --enable-tests
        cabal v2-test
